class BlazzerRunner{
public static void main (String smi[]){

Blazzer blazzer1 = new Blazzer();
System.out.println("the blazer id is:" +blazzer1.blazzerId);
blazzer1.blazzerId=1;
System.out.println("the blazer id is:" +blazzer1.blazzerId);
System.out.println("the blazer material is:" +blazzer1.blazzerMaterial);
blazzer1.blazzerMaterial="cotton";
System.out.println("the blazer material is:" +blazzer1.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer1.price);
blazzer1.price=5000.23;
System.out.println("the blazer price is:" +blazzer1.price);
System.out.println("the blazer price is:" +blazzer1.blazzerSize);
blazzer1.blazzerSize="L";
System.out.println("the blazer price is:" +blazzer1.blazzerSize);
System.out.println("the blazer price is:" +blazzer1.numberOfPockets);
blazzer1.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer1.numberOfPockets);
System.out.println("the blazer price is:" +blazzer1.origin);
blazzer1.origin="India";
System.out.println("the blazer price is:" +blazzer1.origin);
System.out.println("the blazer price is:" +blazzer1.typeOfwash);
blazzer1.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer1.typeOfwash );



Blazzer blazzer2 = new Blazzer();
System.out.println("the blazer id is:" +blazzer2.blazzerId);
blazzer2.blazzerId=2;
System.out.println("the blazer id is:" +blazzer2.blazzerId);
System.out.println("the blazer material is:" +blazzer2.blazzerMaterial);
blazzer2.blazzerMaterial="linen";
System.out.println("the blazer material is:" +blazzer2.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer2.price);
blazzer2.price=8500.56;
System.out.println("the blazer price is:" +blazzer2.price);
System.out.println("the blazer price is:" +blazzer2.blazzerSize);
blazzer2.blazzerSize="XL";
System.out.println("the blazer price is:" +blazzer2.blazzerSize);
System.out.println("the blazer price is:" +blazzer2.numberOfPockets);
blazzer2.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer2.numberOfPockets);
System.out.println("the blazer price is:" +blazzer2.origin);
blazzer2.origin="America";
System.out.println("the blazer price is:" +blazzer2.origin);
System.out.println("the blazer price is:" +blazzer2.typeOfwash);
blazzer2.typeOfwash="Machine wash";
System.out.println("the blazer price is:" +blazzer2.typeOfwash );


Blazzer blazzer3 = new Blazzer();
System.out.println("the blazer id is:" +blazzer3.blazzerId);
blazzer3.blazzerId=3;
System.out.println("the blazer id is:" +blazzer3.blazzerId);
System.out.println("the blazer material is:" +blazzer3.blazzerMaterial);
blazzer3.blazzerMaterial="silk";
System.out.println("the blazer material is:" +blazzer3.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer3.price);
blazzer3.price=12500.56;
System.out.println("the blazer price is:" +blazzer3.price);
System.out.println("the blazer price is:" +blazzer3.blazzerSize);
blazzer3.blazzerSize="M";
System.out.println("the blazer price is:" +blazzer3.blazzerSize);
System.out.println("the blazer price is:" +blazzer3.numberOfPockets);
blazzer3.numberOfPockets=1;
System.out.println("the blazer price is:" +blazzer3.numberOfPockets);
System.out.println("the blazer price is:" +blazzer3.origin);
blazzer3.origin="China";
System.out.println("the blazer price is:" +blazzer3.origin);
System.out.println("the blazer price is:" +blazzer3.typeOfwash);
blazzer3.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer3.typeOfwash );


Blazzer blazzer4 = new Blazzer();
System.out.println("the blazer id is:" +blazzer4.blazzerId);
blazzer4.blazzerId=4;
System.out.println("the blazer id is:" +blazzer4.blazzerId);
System.out.println("the blazer material is:" +blazzer4.blazzerMaterial);
blazzer4.blazzerMaterial="raw silk";
System.out.println("the blazer material is:" +blazzer4.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer4.price);
blazzer4.price=10000.83;
System.out.println("the blazer price is:" +blazzer4.price);
System.out.println("the blazer price is:" +blazzer4.blazzerSize);
blazzer4.blazzerSize="L";
System.out.println("the blazer price is:" +blazzer4.blazzerSize);
System.out.println("the blazer price is:" +blazzer4.numberOfPockets);
blazzer4.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer4.numberOfPockets);
System.out.println("the blazer price is:" +blazzer4.origin);
blazzer4.origin="China";
System.out.println("the blazer price is:" +blazzer4.origin);
System.out.println("the blazer price is:" +blazzer4.typeOfwash);
blazzer4.typeOfwash="machine wash";
System.out.println("the blazer price is:" +blazzer4.typeOfwash);


Blazzer blazzer5 = new Blazzer();
System.out.println("the blazer id is:" +blazzer5.blazzerId);
blazzer5.blazzerId=5;
System.out.println("the blazer id is:" +blazzer5.blazzerId);
System.out.println("the blazer material is:" +blazzer5.blazzerMaterial);
blazzer5.blazzerMaterial="satin silk";
System.out.println("the blazer material is:" +blazzer5.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer5.price);
blazzer5.price=6900.78;
System.out.println("the blazer price is:" +blazzer5.price);
System.out.println("the blazer price is:" +blazzer5.blazzerSize);
blazzer5.blazzerSize="XXL";
System.out.println("the blazer price is:" +blazzer5.blazzerSize);
System.out.println("the blazer price is:" +blazzer5.numberOfPockets);
blazzer5.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer5.numberOfPockets);
System.out.println("the blazer price is:" +blazzer5.origin);
blazzer5.origin="US";
System.out.println("the blazer price is:" +blazzer5.origin);
System.out.println("the blazer price is:" +blazzer5.typeOfwash);
blazzer5.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer5.typeOfwash);

Blazzer blazzer6 = new Blazzer();
System.out.println("the blazer id is:" +blazzer6.blazzerId);
blazzer6.blazzerId=6;
System.out.println("the blazer id is:" +blazzer6.blazzerId);
System.out.println("the blazer material is:" +blazzer6.blazzerMaterial);
blazzer6.blazzerMaterial="cotton silk";
System.out.println("the blazer material is:" +blazzer6.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer6.price);
blazzer6.price=8900.91;
System.out.println("the blazer price is:" +blazzer6.price);
System.out.println("the blazer price is:" +blazzer6.blazzerSize);
blazzer6.blazzerSize="S";
System.out.println("the blazer price is:" +blazzer6.blazzerSize);
System.out.println("the blazer price is:" +blazzer6.numberOfPockets);
blazzer6.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer6.numberOfPockets);
System.out.println("the blazer price is:" +blazzer6.origin);
blazzer6.origin="Tokoyo";
System.out.println("the blazer price is:" +blazzer6.origin);
System.out.println("the blazer price is:" +blazzer6.typeOfwash);
blazzer6.typeOfwash="normal wash";
System.out.println("the blazer price is:" +blazzer6.typeOfwash);


Blazzer blazzer7 = new Blazzer();
System.out.println("the blazer id is:" +blazzer7.blazzerId);
blazzer7.blazzerId=7;
System.out.println("the blazer id is:" +blazzer7.blazzerId);
System.out.println("the blazer material is:" +blazzer7.blazzerMaterial);
blazzer7.blazzerMaterial="tweed";
System.out.println("the blazer material is:" +blazzer7.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer7.price);
blazzer7.price=7899.83;
System.out.println("the blazer price is:" +blazzer7.price);
System.out.println("the blazer price is:" +blazzer7.blazzerSize);
blazzer7.blazzerSize="M";
System.out.println("the blazer price is:" +blazzer7.blazzerSize);
System.out.println("the blazer price is:" +blazzer7.numberOfPockets);
blazzer7.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer7.numberOfPockets);
System.out.println("the blazer price is:" +blazzer7.origin);
blazzer7.origin="India";
System.out.println("the blazer price is:" +blazzer7.origin);
System.out.println("the blazer price is:" +blazzer7.typeOfwash);
blazzer7.typeOfwash="normal wash";
System.out.println("the blazer price is:" +blazzer7.typeOfwash);


Blazzer blazzer8 = new Blazzer();
System.out.println("the blazer id is:" +blazzer8.blazzerId);
blazzer4.blazzerId=8;
System.out.println("the blazer id is:" +blazzer8.blazzerId);
System.out.println("the blazer material is:" +blazzer8.blazzerMaterial);
blazzer8.blazzerMaterial="wool";
System.out.println("the blazer material is:" +blazzer8.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer8.price);
blazzer8.price=2900.83;
System.out.println("the blazer price is:" +blazzer8.price);
System.out.println("the blazer price is:" +blazzer8.blazzerSize);
blazzer8.blazzerSize="S";
System.out.println("the blazer price is:" +blazzer8.blazzerSize);
System.out.println("the blazer price is:" +blazzer8.numberOfPockets);
blazzer8.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer8.numberOfPockets);
System.out.println("the blazer price is:" +blazzer8.origin);
blazzer8.origin="japan";
System.out.println("the blazer price is:" +blazzer8.origin);
System.out.println("the blazer price is:" +blazzer8.typeOfwash);
blazzer8.typeOfwash="machine wash";
System.out.println("the blazer price is:" +blazzer8.typeOfwash);

Blazzer blazzer9 = new Blazzer();
System.out.println("the blazer id is:" +blazzer9.blazzerId);
blazzer9.blazzerId=9;
System.out.println("the blazer id is:" +blazzer9.blazzerId);
System.out.println("the blazer material is:" +blazzer9.blazzerMaterial);
blazzer9.blazzerMaterial="velvet";
System.out.println("the blazer material is:" +blazzer9.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer9.price);
blazzer9.price=6899.83;
System.out.println("the blazer price is:" +blazzer9.price);
System.out.println("the blazer price is:" +blazzer9.blazzerSize);
blazzer9.blazzerSize="XL";
System.out.println("the blazer price is:" +blazzer9.blazzerSize);
System.out.println("the blazer price is:" +blazzer9.numberOfPockets);
blazzer9.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer9.numberOfPockets);
System.out.println("the blazer price is:" +blazzer9.origin);
blazzer9.origin="India";
System.out.println("the blazer price is:" +blazzer9.origin);
System.out.println("the blazer price is:" +blazzer9.typeOfwash);
blazzer9.typeOfwash="normal wash";
System.out.println("the blazer price is:" +blazzer9.typeOfwash);


Blazzer blazzer10 = new Blazzer();
System.out.println("the blazer id is:" +blazzer10.blazzerId);
blazzer10.blazzerId=10;
System.out.println("the blazer id is:" +blazzer10.blazzerId);
System.out.println("the blazer material is:" +blazzer10.blazzerMaterial);
blazzer10.blazzerMaterial=" blazzer silk";
System.out.println("the blazer material is:" +blazzer10.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer10.price);
blazzer10.price=45000.92;
System.out.println("the blazer price is:" +blazzer10.price);
System.out.println("the blazer price is:" +blazzer10.blazzerSize);
blazzer10.blazzerSize="XL";
System.out.println("the blazer price is:" +blazzer10.blazzerSize);
System.out.println("the blazer price is:" +blazzer10.numberOfPockets);
blazzer10.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer10.numberOfPockets);
System.out.println("the blazer price is:" +blazzer10.origin);
blazzer10.origin="germany";
System.out.println("the blazer price is:" +blazzer10.origin);
System.out.println("the blazer price is:" +blazzer10.typeOfwash);
blazzer10.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer10.typeOfwash);

Blazzer blazzer11 = new Blazzer();
System.out.println("the blazer id is:" +blazzer11.blazzerId);
blazzer11.blazzerId=11;
System.out.println("the blazer id is:" +blazzer11.blazzerId);
System.out.println("the blazer material is:" +blazzer11.blazzerMaterial);
blazzer11.blazzerMaterial="raw cotton";
System.out.println("the blazer material is:" +blazzer11.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer11.price);
blazzer11.price=3689.41;
System.out.println("the blazer price is:" +blazzer11.price);
System.out.println("the blazer price is:" +blazzer11.blazzerSize);
blazzer11.blazzerSize="S";
System.out.println("the blazer price is:" +blazzer11.blazzerSize);
System.out.println("the blazer price is:" +blazzer11.numberOfPockets);
blazzer11.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer11.numberOfPockets);
System.out.println("the blazer price is:" +blazzer11.origin);
blazzer11.origin="US";
System.out.println("the blazer price is:" +blazzer11.origin);
System.out.println("the blazer price is:" +blazzer11.typeOfwash);
blazzer11.typeOfwash="normal wash";
System.out.println("the blazer price is:" +blazzer11.typeOfwash);



Blazzer blazzer12 = new Blazzer();
System.out.println("the blazer id is:" +blazzer12.blazzerId);
blazzer12.blazzerId=12;
System.out.println("the blazer id is:" +blazzer12.blazzerId);
System.out.println("the blazer material is:" +blazzer12.blazzerMaterial);
blazzer12.blazzerMaterial="cotton silk";
System.out.println("the blazer material is:" +blazzer12.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer12.price);
blazzer12.price=5999.03;
System.out.println("the blazer price is:" +blazzer12.price);
System.out.println("the blazer price is:" +blazzer12.blazzerSize);
blazzer12.blazzerSize="XL";
System.out.println("the blazer price is:" +blazzer12.blazzerSize);
System.out.println("the blazer price is:" +blazzer12.numberOfPockets);
blazzer12.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer12.numberOfPockets);
System.out.println("the blazer price is:" +blazzer12.origin);
blazzer12.origin="India";
System.out.println("the blazer price is:" +blazzer12.origin);
System.out.println("the blazer price is:" +blazzer12.typeOfwash);
blazzer12.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer12.typeOfwash);


Blazzer blazzer13 = new Blazzer();
System.out.println("the blazer id is:" +blazzer13.blazzerId);
blazzer13.blazzerId=13;
System.out.println("the blazer id is:" +blazzer13.blazzerId);
System.out.println("the blazer material is:" +blazzer13.blazzerMaterial);
blazzer13.blazzerMaterial="silk nylon";
System.out.println("the blazer material is:" +blazzer13.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer13.price);
blazzer13.price=7452.41;
System.out.println("the blazer price is:" +blazzer13.price);
System.out.println("the blazer price is:" +blazzer13.blazzerSize);
blazzer13.blazzerSize="XS";
System.out.println("the blazer price is:" +blazzer13.blazzerSize);
System.out.println("the blazer price is:" +blazzer13.numberOfPockets);
blazzer13.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer13.numberOfPockets);
System.out.println("the blazer price is:" +blazzer13.origin);
blazzer13.origin="Australia";
System.out.println("the blazer price is:" +blazzer13.origin);
System.out.println("the blazer price is:" +blazzer13.typeOfwash);
blazzer13.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer13.typeOfwash);


Blazzer blazzer14 = new Blazzer();
System.out.println("the blazer id is:" +blazzer14.blazzerId);
blazzer14.blazzerId=14;
System.out.println("the blazer id is:" +blazzer14.blazzerId);
System.out.println("the blazer material is:" +blazzer14.blazzerMaterial);
blazzer14.blazzerMaterial="dopian";
System.out.println("the blazer material is:" +blazzer14.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer14.price);
blazzer14.price=4879.83;
System.out.println("the blazer price is:" +blazzer14.price);
System.out.println("the blazer price is:" +blazzer14.blazzerSize);
blazzer14.blazzerSize="M";
System.out.println("the blazer price is:" +blazzer14.blazzerSize);
System.out.println("the blazer price is:" +blazzer14.numberOfPockets);
blazzer14.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer14.numberOfPockets);
System.out.println("the blazer price is:" +blazzer14.origin);
blazzer14.origin="tokoyo";
System.out.println("the blazer price is:" +blazzer14.origin);
System.out.println("the blazer price is:" +blazzer14.typeOfwash);
blazzer14.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer14.typeOfwash);


Blazzer blazzer15 = new Blazzer();
System.out.println("the blazer id is:" +blazzer15.blazzerId);
blazzer15.blazzerId=15;
System.out.println("the blazer id is:" +blazzer15.blazzerId);
System.out.println("the blazer material is:" +blazzer15.blazzerMaterial);
blazzer15.blazzerMaterial="weep silk";
System.out.println("the blazer material is:" +blazzer15.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer15.price);
blazzer15.price=9999.74;
System.out.println("the blazer price is:" +blazzer15.price);
System.out.println("the blazer price is:" +blazzer15.blazzerSize);
blazzer15.blazzerSize="M";
System.out.println("the blazer price is:" +blazzer15.blazzerSize);
System.out.println("the blazer price is:" +blazzer15.numberOfPockets);
blazzer15.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer15.numberOfPockets);
System.out.println("the blazer price is:" +blazzer15.origin);
blazzer15.origin="Afganistan";
System.out.println("the blazer price is:" +blazzer15.origin);
System.out.println("the blazer price is:" +blazzer15.typeOfwash);
blazzer15.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer15.typeOfwash);


Blazzer blazzer16 = new Blazzer();
System.out.println("the blazer id is:" +blazzer16.blazzerId);
blazzer16.blazzerId=16;
System.out.println("the blazer id is:" +blazzer4.blazzerId);
System.out.println("the blazer material is:" +blazzer16.blazzerMaterial);
blazzer16.blazzerMaterial=" silk";
System.out.println("the blazer material is:" +blazzer16.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer16.price);
blazzer16.price=15899.83;
System.out.println("the blazer price is:" +blazzer16.price);
System.out.println("the blazer price is:" +blazzer16.blazzerSize);
blazzer16.blazzerSize="L";
System.out.println("the blazer price is:" +blazzer16.blazzerSize);
System.out.println("the blazer price is:" +blazzer16.numberOfPockets);
blazzer16.numberOfPockets=16;
System.out.println("the blazer price is:" +blazzer16.numberOfPockets);
System.out.println("the blazer price is:" +blazzer16.origin);
blazzer16.origin="germany";
System.out.println("the blazer price is:" +blazzer16.origin);
System.out.println("the blazer price is:" +blazzer16.typeOfwash);
blazzer16.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer16.typeOfwash);


Blazzer blazzer17 = new Blazzer();
System.out.println("the blazer id is:" +blazzer17.blazzerId);
blazzer17.blazzerId=17;
System.out.println("the blazer id is:" +blazzer17.blazzerId);
System.out.println("the blazer material is:" +blazzer17.blazzerMaterial);
blazzer17.blazzerMaterial="raw cotton";
System.out.println("the blazer material is:" +blazzer17.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer17.price);
blazzer17.price=5689.83;
System.out.println("the blazer price is:" +blazzer17.price);
System.out.println("the blazer price is:" +blazzer17.blazzerSize);
blazzer17.blazzerSize="S";
System.out.println("the blazer price is:" +blazzer17.blazzerSize);
System.out.println("the blazer price is:" +blazzer17.numberOfPockets);
blazzer17.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer17.numberOfPockets);
System.out.println("the blazer price is:" +blazzer17.origin);
blazzer17.origin="India";
System.out.println("the blazer price is:" +blazzer17.origin);
System.out.println("the blazer price is:" +blazzer17.typeOfwash);
blazzer17.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer17.typeOfwash);


Blazzer blazzer18 = new Blazzer();
System.out.println("the blazer id is:" +blazzer18.blazzerId);
blazzer18.blazzerId=18;
System.out.println("the blazer id is:" +blazzer4.blazzerId);
System.out.println("the blazer material is:" +blazzer18.blazzerMaterial);
blazzer18.blazzerMaterial="shiffon satin";
System.out.println("the blazer material is:" +blazzer18.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer18.price);
blazzer18.price=8253.83;
System.out.println("the blazer price is:" +blazzer18.price);
System.out.println("the blazer price is:" +blazzer18.blazzerSize);
blazzer18.blazzerSize="M";
System.out.println("the blazer price is:" +blazzer18.blazzerSize);
System.out.println("the blazer price is:" +blazzer18.numberOfPockets);
blazzer18.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer18.numberOfPockets);
System.out.println("the blazer price is:" +blazzer18.origin);
blazzer18.origin="turkey";
System.out.println("the blazer price is:" +blazzer18.origin);
System.out.println("the blazer price is:" +blazzer18.typeOfwash);
blazzer18.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer18.typeOfwash);

Blazzer blazzer19 = new Blazzer();
System.out.println("the blazer id is:" +blazzer19.blazzerId);
blazzer19.blazzerId=19;
System.out.println("the blazer id is:" +blazzer19.blazzerId);
System.out.println("the blazer material is:" +blazzer19.blazzerMaterial);
blazzer19.blazzerMaterial="raw silk";
System.out.println("the blazer material is:" +blazzer19.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer19.price);
blazzer19.price=10000.83;
System.out.println("the blazer price is:" +blazzer19.price);
System.out.println("the blazer price is:" +blazzer19.blazzerSize);
blazzer19.blazzerSize="L";
System.out.println("the blazer price is:" +blazzer19.blazzerSize);
System.out.println("the blazer price is:" +blazzer19.numberOfPockets);
blazzer19.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer19.numberOfPockets);
System.out.println("the blazer price is:" +blazzer19.origin);
blazzer19.origin="China";
System.out.println("the blazer price is:" +blazzer19.origin);
System.out.println("the blazer price is:" +blazzer19.typeOfwash);
blazzer19.typeOfwash="machine wash";
System.out.println("the blazer price is:" +blazzer19.typeOfwash);


Blazzer blazzer20 = new Blazzer();
System.out.println("the blazer id is:" +blazzer20.blazzerId);
blazzer20.blazzerId=20;
System.out.println("the blazer id is:" +blazzer20.blazzerId);
System.out.println("the blazer material is:" +blazzer20.blazzerMaterial);
blazzer20.blazzerMaterial="linen";
System.out.println("the blazer material is:" +blazzer20.blazzerMaterial);
System.out.println("the blazer price is:" +blazzer20.price);
blazzer20.price=4589.83;
System.out.println("the blazer price is:" +blazzer20.price);
System.out.println("the blazer price is:" +blazzer20.blazzerSize);
blazzer20.blazzerSize="XL";
System.out.println("the blazer price is:" +blazzer20.blazzerSize);
System.out.println("the blazer price is:" +blazzer20.numberOfPockets);
blazzer20.numberOfPockets=2;
System.out.println("the blazer price is:" +blazzer20.numberOfPockets);
System.out.println("the blazer price is:" +blazzer20.origin);
blazzer20.origin="India";
System.out.println("the blazer price is:" +blazzer20.origin);
System.out.println("the blazer price is:" +blazzer20.typeOfwash);
blazzer20.typeOfwash="dry wash";
System.out.println("the blazer price is:" +blazzer20.typeOfwash);
}
}
